title: Praveen Kumar Sridhar
url: "https://praveenkumarsridhar.github.io"
baseurl: "/PraveenKumarS"
markdown: kramdown

collections:
  notes:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note

exclude:
  - README.md
