title: Praveen Kumar Sridhar
url: "https://praveenks.com"
baseurl: ""
markdown: kramdown

collections:
  notes:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note

exclude:
  - README.md
